### ISSUE TITLE
Restore from S3 not possible - S3 Backups filtered out

### ISSUE THREAD

**Issue by eugeis** [codestation/go-s3-backup#2]
Hello, 
great tool, thank you!

A backup from Postgres DB top S3 works fine, but a Restore ist not working. I debugged a bit and S3 objects are retrieved correctly from S3, but then they are filtered out by this function/regexp.

`
S3.go/S3Config Type,  line number 110.  

// ignore files not created by this program
				if re.MatchString(path.Base(aws.StringValue(obj.Key))) {
					files = append(files, aws.StringValue(obj.Key))
				}
`

The regular expression at line 99 is build with empty namePrefix and therefore it can't work I think.

I am using this parameters for backup and restore

DATABASE_HOST_BACKUP=172.17.0.1
DATABASE_HOST_RESTORE=172.17.0.1
DATABASE_PORT=5432
DATABASE_NAME=dbname
DATABASE_USER=postgres
DATABASE_PASSWORD=xy
DATABASE_NAME_AS_PREFIX=true
S3_ENDPOINT=s3.amazonaws.com
S3_REGION=eu-central-1
S3_BUCKET=bucketname
S3_PREFIX=backup
AWS_ACCESS_KEY_ID=xy
AWS_SECRET_ACCESS_KEY=xykey
SCHEDULE=none
DATABASE_COMPRESS=true
POSTGRES_CUSTOM_FORMAT=true

**Comment by codestation** [comment]
Currently i am not using the restore functionality so it went unmaintained, sorry about that. Since you are using `DATABASE_NAME_AS_PREFIX`, i added a `RESTORE_PREFIX` config option so you can use the database name as the prefix and the regex will work again.

If the database already exists then the restore will fail, so you have two options:

* `POSTGRES_DROP=true`: this will kill all the connections to the database, then drop it and create an empty database before restoring it.
* `DATABASE_OPTIONS=--clean`: it will pass the flag to pg_restore so the database will be dropped (or a schema if you didn't dump the whole database).
